### ISSUE TITLE
How to display the mAcc figure？

### ISSUE THREAD

**Issue by matrixgame2018** [matrixgame2018/FEANet#1]
In this paper, the mAcc is not the accuracy， just the recall function.

**Comment by LiuzhuForFun** [comment]
**precision_per_class**, recall_per_class, iou_per_class = compute_results(conf_total)

**Comment by LiuzhuForFun** [comment]
Why existing methods cannot provide their trained models or codes? (e.g., CVPR 21, AAAI 22)
