### ISSUE TITLE
About FPS, eval_time, flops and params.

### ISSUE THREAD

**Issue by Mask0913** [matrixgame2018/FEANet#3]
This is a good job. But, i have a question.  How to achieve the real-time spped， your backbone in my 3090 only get 0.38s infer time, only 2.6FPS. I calculated using FEANet. py and Thop in your code。May I ask if there are any issues with my operation？
FEANet：eval_time: 0.36808860778808594s flops: 674.938934128G params: 255.20713M

**Comment by matrixgame2018** [comment]
I think the article's expression of real-time performance is mainly focused on adding the FEAM module, which does not add additional inferences burden compared to the RTFNet model that claims real-time.

On the task of accelerating model inference, here are some tips

1、TRT can help you optimize and speed up your model.

2、Use the ResNet50 or smaller parmater backbone

3、You also can design a light decoder to help you reduce the burden of inference
